<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJnRl1be\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJnRl1be/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJnRl1be.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJnRl1be\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerJnRl1be\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'JnRl1be',
    'container.build_id' => '9830f9e5',
    'container.build_time' => 1579966847,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJnRl1be');
