<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS9uBpyv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS9uBpyv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS9uBpyv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS9uBpyv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerS9uBpyv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'S9uBpyv',
    'container.build_id' => '677ea0a4',
    'container.build_time' => 1580673546,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS9uBpyv');
