<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'use_json_respons' => [[], ['_controller' => 'App\\Controller\\UseJsonResponsController::index'], [], [['text', '/jsonRespons/index']], [], []],
    'jsonRespons' => [[], ['_controller' => 'App\\Controller\\UseJsonResponsController::jsonRespons'], [], [['text', '/json_respons']], [], []],
    'site_respons' => [['id'], ['_controller' => 'App\\Controller\\UseJsonResponsController::siteRespons'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/site_respons']], [], []],
    'use_service_index' => [[], ['_controller' => 'App\\Controller\\UseServiceController::index'], [], [['text', '/useservice/index/']], [], []],
    'useservice' => [['username'], ['_controller' => 'App\\Controller\\UseServiceController::useService'], [], [['variable', '/', '[^/]++', 'username'], ['text', '/useservice']], [], []],
    'useserviceEx' => [['username'], ['_controller' => 'App\\Controller\\UseServiceController::useServiceEx'], [], [['variable', '/', '[^/]++', 'username'], ['text', '/useserviceEx']], [], []],
];
